### ISSUE TITLE
Cannot start without `--exit-codeword`

### ISSUE THREAD

**Issue by JensRantil** [JensRantil/rewind#28]
If not specified, one gets:

``` bash
$ ../bin/rewind --incoming-bind-endpoint inproc://swp-incoming-evs --streaming-bind-endpoint inproc://not-used
No handlers could be found for logger "rewind.rewind"
Traceback (most recent call last):
  File "../bin/rewind", line 8, in <module>
    load_entry_point('rewind==0.1.1', 'console_scripts', 'rewind')()
  File "/Users/jens/Development/src/my_projects/rewind/src/rewind/rewind.py", line 364, in main
    exitcode = run(args)
  File "/Users/jens/Development/src/my_projects/rewind/src/rewind/rewind.py", line 280, in run
    streaming_socket, args.exit_message.encode())
AttributeError: 'NoneType' object has no attribute 'encode'
```

This is a fairly serious bug.

**Comment by JensRantil** [comment]
Fixed in version 0.1.2.
